//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawy
    {
        public int IdDostawy { get; set; }
        public Nullable<int> IdRestauracji { get; set; }
        public Nullable<int> IdZamowienia { get; set; }
        public string AdresDostawy { get; set; }
        public System.DateTime DataDostawy { get; set; }
    
        public virtual Restauracje Restauracje { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
