//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozycjeZamowienia
    {
        public int IdPozycjaZamowienia { get; set; }
        public Nullable<int> IdZamowienia { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public int Ilosc { get; set; }
        public decimal Cena { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
