//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia()
        {
            this.Dostawy = new HashSet<Dostawy>();
            this.HistoriaZamowien = new HashSet<HistoriaZamowien>();
            this.PozycjeZamowienia = new HashSet<PozycjeZamowienia>();
        }
    
        public int IdZamowienia { get; set; }
        public Nullable<int> IdRestauracji { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Suma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawy> Dostawy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaZamowien> HistoriaZamowien { get; set; }
        public virtual Klienci Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeZamowienia> PozycjeZamowienia { get; set; }
        public virtual Restauracje Restauracje { get; set; }
    }
}
